apiVersion: v1
kind: ConfigMap
metadata:
  name: kitchensink-spring-config
  labels:
    app: kitchensink-spring
data:
  application.properties: |
    # Server configuration
    server.port=8080
    
    # Database Configuration
    spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:kitchensink}
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
    spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    
    # JPA Configuration
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    
    # Thymeleaf configuration
    spring.thymeleaf.cache=true
    
    # OpenAPI settings
    springdoc.swagger-ui.path=/swagger-ui.html
    springdoc.api-docs.path=/v3/api-docs