apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchensink-spring-data
  labels:
    app: kitchensink-spring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi