apiVersion: v2
name: kitchensink-spring
description: A Helm chart for the Kitchensink Spring Boot application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - spring-boot
  - kitchensink
  - java
maintainers:
  - name: JBoss Developer
    email: developer@jboss.org